name: "Hello Actions"

description: "Greet someone"

author: "octocat@github.com"



inputs:

  Ashton:

    description: "Who to greet"

    required: true

    default: "World"



runs:

  using: "docker"

  image: "Dockerfile"



branding:

  icon: "mic"

  color: "purple"